server:
  port: 8084

spring:
  application:
    name: recommend-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      eager: true

feign:
  sentinel:
    enabled: true

jwt:
  secret: smart-campus-course-selection-jwt-secret-2026-xwt
  expire-hours: 24

logging:
  level:
    com.smartcampus: info
